name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plots-${{ matrix.os }}
        path: |
          result/share/assets
